// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xroodyecijlzwcqtnlxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhyb29keWVjaWpsendjcXRubHhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NjU3NTEsImV4cCI6MjA3NDI0MTc1MX0.dMLyCJi5jgpgKj0JgsMyBNGaGBlCC9Wb3nKP7yA53NQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});